version: '3.8'

services:
  db:
    image: arm64v8/mysql:8.0
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lms
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
